import logging
import httpx
from email.mime.text import MIMEText
from app.core.config import settings

logger = logging.getLogger("email_notifier")


class EmailNotifier:
    async def send_email(self, subject: str, body: str) -> None:
        to = settings.NOTIFICATION_EMAIL_TO
        if not to:
            logger.debug("NOTIFICATION_EMAIL_TO not set – skipping email.")
            return

        if settings.SENDGRID_API_KEY:
            await self._send_sendgrid(to, subject, body)
        elif settings.SMTP_HOST:
            await self._send_smtp(to, subject, body)
        else:
            logger.debug("No email provider configured – skipping email.")

    async def _send_sendgrid(self, to: str, subject: str, body: str) -> None:
        url = "https://api.sendgrid.com/v3/mail/send"
        headers = {
            "Authorization": f"Bearer {settings.SENDGRID_API_KEY}",
            "Content-Type": "application/json",
        }
        payload = {
            "personalizations": [{"to": [{"email": to}]}],
            "from": {"email": settings.SMTP_FROM or "ops-pilot@noreply.com"},
            "subject": subject,
            "content": [{"type": "text/plain", "value": body}],
        }
        async with httpx.AsyncClient() as client:
            try:
                resp = await client.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                logger.info(f"SendGrid email sent to {to}")
            except Exception as e:
                logger.error(f"SendGrid email failed: {e}")

    async def _send_smtp(self, to: str, subject: str, body: str) -> None:
        try:
            import smtplib
            msg = MIMEText(body)
            msg["Subject"] = subject
            msg["From"] = settings.SMTP_FROM or "ops-pilot@noreply.com"
            msg["To"] = to
            with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
                if settings.SMTP_USER:
                    server.starttls()
                    server.login(settings.SMTP_USER, settings.SMTP_PASSWORD or "")
                server.send_message(msg)
            logger.info(f"SMTP email sent to {to}")
        except Exception as e:
            logger.error(f"SMTP email failed: {e}")

    async def notify_failure(self, repo_name: str, run_id: int, status: str, error_details: dict | None) -> None:
        subject = f"[Ops-Pilot] CI Failure: {repo_name} Run #{run_id}"
        body_lines = [
            f"Repository: {repo_name}",
            f"Run ID: #{run_id}",
            f"Status: {status}",
            f"Run URL: https://github.com/{repo_name}/actions/runs/{run_id}",
        ]
        if error_details:
            body_lines.extend([
                "",
                f"Error Type: {error_details.get('error_type', 'Unknown')}",
                f"Error Message: {error_details.get('error_message', 'N/A')}",
                f"File: {error_details.get('filename', 'N/A')}:{error_details.get('line_number', '?')}",
            ])
        body_lines.append("")
        body_lines.append("Generated by Ops-Pilot")
        await self.send_email(subject, "\n".join(body_lines))


email_notifier = EmailNotifier()
